services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: open-memory-api
    command: uv run gunicorn --bind 0.0.0.0:${API_PORT} "app:create_app('production')"
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - DATABASE_URL=postgresql+psycopg://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - LLM_MODEL_API_KEY=${LLM_MODEL_API_KEY}
      - LLM_MODEL_BASE_URL=${LLM_MODEL_BASE_URL}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - EMBEDDING_MODEL_API_KEY=${EMBEDDING_MODEL_API_KEY}
      - EMBEDDING_MODEL_BASE_URL=${EMBEDDING_MODEL_BASE_URL}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION}
      - API_AUTH_TOKEN=${API_AUTH_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: open-memory-worker
    command: uv run celery -A app.celery worker --loglevel=info
    environment:
      - FLASK_APP=app
      - DATABASE_URL=postgresql+psycopg://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - LLM_MODEL_API_KEY=${LLM_MODEL_API_KEY}
      - LLM_MODEL_BASE_URL=${LLM_MODEL_BASE_URL}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - EMBEDDING_MODEL_API_KEY=${EMBEDDING_MODEL_API_KEY}
      - EMBEDDING_MODEL_BASE_URL=${EMBEDDING_MODEL_BASE_URL}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: pgvector/pgvector:pg15
    container_name: open-memory-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: open-memory-redis
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"
