"""Update task model

Revision ID: 68815f4198d3
Revises: 6997adf3f49c
Create Date: 2026-03-05 11:31:14.209117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68815f4198d3'
down_revision = '6997adf3f49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('error')

    # ### end Alembic commands ###
